
init:
	wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
	tar xzvf dynamodb_local_latest.tar.gz

start:
	java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar
