create-table:
	sh script/create-table.sh

create-index:
	sh script/create-index.sh

insert-seed:
	sh script/insert-seed.sh

scan:
	sh script/scan-table.sh

delete-table:
	sh script/delete-table.sh

delete-index:
	sh script/delete-index.sh

describe-table:
	sh script/describe-table.sh
